// Golden deck — the FULL visual reference of the kit: every slide template, the structure pages
// (dark & light covers, agenda, divider) and an exhibit gallery (native charts, SVG exhibits,
// craft primitives, dark KPI strip). Realistic content (fictional case). Serves as visual
// reference AND as a copy source.
// Run: node examples/golden-deck.js [outdir]  (then scripts/effects.py + scripts/rezip.py)
const path = require("path");
const ROOT = path.join(__dirname, "..");
const pptxgen = require(path.join(ROOT, "node_modules/pptxgenjs"));
const svgKit = require(path.join(ROOT, "assets/svg.cjs"));
const outdir = process.argv[2] || __dirname;

(async () => {

// ---- async pre-generation (SVG exhibits) BEFORE the synchronous build --------------------
const FX = path.join(__dirname, "gd-assets");
const ACC = "2E7CF6", ACC_D = "1D5FCC";
const svgSlope = await svgKit.render(svgKit.slope({ leftLabel: "2025", rightLabel: "2029E", color: ACC, items: [
  { label: "Services", a: 46, b: 48 },
  { label: "Group", a: 28, b: 34, highlight: true },
  { label: "Equipment", a: 20, b: 19 } ] }), FX, "slope");
const svgDumbbell = await svgKit.render(svgKit.dumbbell({ aLabel: "Today", bLabel: "2029 target", colorB: ACC, items: [
  { label: "Parts capture %", a: 31, b: 60 },
  { label: "Contract attach %", a: 12, b: 26 },
  { label: "Technician utilization %", a: 61, b: 78 } ] }), FX, "dumbbell");
const svgMekko = await svgKit.render(svgKit.mekko({ cols: [
  { label: "Equipment (65%)", weight: 65, segs: [ { value: 60, color: ACC }, { value: 40, color: "AFC9F0" } ] },
  { label: "Services (35%)", weight: 35, segs: [ { value: 45, color: ACC }, { value: 35, color: "5AA0FF" }, { value: 20, color: "AFC9F0" } ] } ] }), FX, "mekko");
const svgWaffle = await svgKit.render(svgKit.waffle({ value: 31, color: ACC, label: "31%", sub: "parts spend captured" }), FX, "waffle");
const svgVenn = await svgKit.render(svgKit.venn({ center: "Premium", sets: [ { label: "Uptime need" }, { label: "Field coverage" }, { label: "Usage data" } ] }), FX, "venn");

const pres = new pptxgen(); pres.layout = "LAYOUT_WIDE";
const kit = require(path.join(ROOT, "assets/deck_helpers.js"))(pres); // neutral default accent
const tpl = require(path.join(ROOT, "assets/slide_templates.js"))(pres, kit);

const TRK = { sections: ["Context", "Diagnosis", "Options", "Execution"], active: 1 };
const SRC = "Source: Meridio annual reports 2022-2025; management interviews; Sprint OS analysis";
let pg = 0; const P = () => ++pg;

// 0a. DARK cover (plain dark background; in production: gen_bg.cjs PNG)
kit.coverDark(pres.addSlide(), { eyebrow: "GOLDEN DECK — TEMPLATE SHOWCASE", title: "Meridio Group",
  governing: "Every slide in this deck is generated by a template from slide_templates.js: guaranteed geometry, injected content.",
  metaA: "Sprint OS Deck Builder", metaB: "Internal demo", metaC: "July 2026", metaD: "Confidential", source: SRC });

// 0b. LIGHT cover — the DEFAULT cover style (here: "arcs"; 8 compositions available)
kit.coverLight(pres.addSlide(), { eyebrow: "LIGHT COVER (DEFAULT) — STYLE: ARCS", style: "arcs",
  title: "Doubling EBITDA on assets already paid for",
  governing: "Meridio can shift 60% of 2027-2029 capex to managed services: the installed base, not new sales, carries the next growth cycle.",
  metaA: "Sprint OS Deck Builder", metaB: "Internal demo", metaC: "July 2026", metaD: "Confidential", source: SRC });

// 0c. AGENDA (dark structured page: darkHeader + numbered sections)
{
  const s = pres.addSlide();
  kit.darkHeader(s, null, "AGENDA", "Four parts, one decision to take in September");
  const items = [
    ["01", "Context", "The core-market slowdown is structural, not cyclical"],
    ["02", "Diagnosis", "Where the margin leaks: four findings on the installed base"],
    ["03", "Options", "Three entry routes into managed services, one recommendation"],
    ["04", "Execution", "Pilot, roadmap, governance and the first 100 days"]];
  items.forEach((it, i) => { const y = 2.35 + i * 1.02;
    s.addText(it[0], { x: 0.85, y, w: 0.75, h: 0.5, fontFace: kit.THEME.fMono, fontSize: 20, bold: true, color: kit.THEME.accentOnDark, margin: 0 });
    s.addText(it[1], { x: 1.75, y, w: 3.6, h: 0.5, fontFace: kit.THEME.fDisp, fontSize: 19, bold: true, color: kit.THEME.don, margin: 0 });
    s.addText(it[2], { x: 5.6, y: y + 0.04, w: 7.1, h: 0.5, fontFace: kit.THEME.fBody, fontSize: 13, color: kit.THEME.dmute, margin: 0 });
    if (i < items.length - 1) s.addShape(pres.shapes.LINE, { x: 0.85, y: y + 0.78, w: 11.85, h: 0, line: { color: kit.THEME.dline, width: 0.5 } }); });
  s.addText("Objective: decide the entry route into managed services before the 2027 budget.", {
    x: 0.85, y: 6.65, w: 11.8, h: 0.4, fontFace: kit.THEME.fBody, fontSize: 12.5, italic: true, color: kit.THEME.dmute, margin: 0 });
}

// 1. execSummary3
tpl.execSummary3(pres.addSlide(), { eyebrow: "EXECUTIVE SUMMARY", tracker: TRK,
  title: "Meridio can double its EBITDA by 2029 by concentrating investment on the services segment",
  messages: [
    { head: "The core market is slowing down", body: "Equipment market growth has fallen from 6.1% per year (2019-2022) to 1.8% (2023-2025), a structural ceiling driven by the equipment penetration rate.",
      implication: ["The current plan, built on 5% growth, overstates 2029 revenue by EUR 210M", "Every year of waiting narrows the repositioning window"] },
    { head: "Services already drive the margin", body: "Services account for 22% of revenue but 41% of 2025 gross margin; their organic growth reaches 14% per year without any dedicated investment.",
      implication: ["A 35% services mix would lift group margin from 28% to 34%", "The installed base (18,400 sites) is an under-monetized asset", "An installed-base contract costs 5x less to acquire than a new sale"] },
    { head: "The competitive window is short", body: "Two competitors have announced managed-services offers; neither yet matches Meridio's field coverage (94% of the territory).",
      implication: ["The coverage advantage erodes within 24-36 months", "The first mover historically captures 60% of the segment", "Waiting until 2028 would halve the program's net present value"] }],
  bottomLine: "Shifting 60% of 2027-2029 capex to services doubles EBITDA and protects the core market.",
  bandLabel: "Bottom line", source: SRC, page: P() });

// 2. memoQuadrants
tpl.memoQuadrants(pres.addSlide(), { eyebrow: "CONTEXT", tracker: { ...TRK, active: 0 },
  title: "The core market slowdown is structural, not cyclical",
  summary: { head: "The essentials", body: "Four readings converge: the equipment market has reached its maximum penetration rate, and residual growth is shifting toward usage and maintenance of the installed base.\n\nThis shift is not cyclical: it follows the equipment curve observed in Germany (2018) and Italy (2021), two markets where new-equipment sales never returned to their previous level.\n\nThe question is therefore not how to protect new-equipment sales, but how to organize the capture of usage value before competitors do." },
  sections: [
    { head: "Finding", body: "The volume of new units sold in France has been declining by 2.4% per year since 2023, while the installed base keeps growing (+3.1% per year). The market is shifting from new sales to servicing the existing base: maintenance spending on the installed base is growing 5.8% per year over the same period, and no national player is consolidating it." },
    { head: "Cause", body: "The equipment penetration rate of target industrial sites has reached 87%, versus 64% in 2015. First-equipment demand, Meridio's historical growth engine, is mechanically drying up: roughly 2,600 equippable sites remain, versus 11,000 in 2015, and commissioning of new industrial sites does not compensate (about 400 per year)." },
    { head: "Consequence", body: "At constant plan, equipment revenue plateaus at EUR 640M in 2029 (versus EUR 850M budgeted). The EUR 210M gap cannot be closed through pricing: measured elasticity is -1.8, and competitive pressure on tenders has already compressed the average price by 3.1% in 2025." },
    { head: "Implication", body: "Growth must come from monetizing the installed base: predictive maintenance, parts, training, remote monitoring. It is the only growth lever built on assets already paid for (field coverage, usage data, brand) rather than on costly conquest, and the only one compatible with the timeline: every quarter of waiting lets 2,300 maintenance contracts be signed elsewhere." }],
  source: SRC, page: P() });

// 3. sideIndex
tpl.sideIndex(pres.addSlide(), { eyebrow: "APPROACH", tracker: { ...TRK, active: 0 },
  title: "The diagnosis rests on eight analyses, all documented in the appendix",
  index: [ { n: 1, label: "Market sizing" }, { n: 2, label: "Installed-base analysis", active: true },
    { n: 3, label: "Customer interviews (n=42)" }, { n: 4, label: "Competitor benchmark" },
    { n: 5, label: "Services economics" }, { n: 6, label: "Internal capabilities" },
    { n: 7, label: "Financial scenarios" }, { n: 8, label: "Implementation plan" } ],
  bodyHead: "Analysis 2: the installed base, the central asset of the case",
  body: [
    { lead: "The 18,400-site installed base is Meridio's foremost strategic asset.", text: "Each site generates on average EUR 4,200 per year in maintenance and parts spending, of which Meridio captures only 31% today. The rest goes to independent maintainers, less well equipped but more present commercially." },
    { lead: "Usage data changes the economic equation.", text: "Across the 6,800 connected sites, the avoidable-failure rate reaches 38%: predictive maintenance would support selling a premium contract while cutting intervention costs by 22%." },
    { lead: "Field coverage is a defensible advantage.", text: "94% of sites are within two hours of a Meridio technician, versus 61% for the best-placed competitor. This gap, costly to replicate, justifies a price premium measured at 8-12% in the customer interviews." }],
  source: SRC, page: P() });

// 4. keyMessagesSoWhat
tpl.keyMessagesSoWhat(pres.addSlide(), { eyebrow: "DIAGNOSIS", tracker: TRK,
  title: "Four findings command the shift to services",
  items: [
    { head: "New-equipment sales are plateauing: -2.4% per year since 2023", sub: "Target penetration rate reached (87%)" },
    { head: "Services deliver 41% of the margin with 22% of revenue", sub: "14% organic growth per year, without investment" },
    { head: "69% of installed-base maintenance escapes Meridio", sub: "Captured by less well-equipped independents" },
    { head: "Two competitors are preparing managed offers", sub: "Q1 2026 announcements; field coverage still inferior" }],
  soWhat: { body: "The status quo protects neither revenue (new-sales ceiling) nor margin (maintenance leakage).\n\nThe services shift is not one growth option among others: it is the only one built on an advantage already paid for — the installed base and field coverage.\n\nTiming is the real decision at stake: all four findings are deteriorating in the same direction, and two of them (competition, maintenance attrition) are irreversible once contracts are signed elsewhere.\n\nHence the recommendation to decide at the September committee, before the 2027 budget." },
  source: SRC, page: P() });

// 5. decisionNote
tpl.decisionNote(pres.addSlide(), { eyebrow: "DECISION", tracker: { ...TRK, active: 2 },
  title: "Three entry routes into managed services, only one maximizes the value of the installed base",
  need: { body: "The committee must decide on the entry route into managed services before the 2027 budget. The choice commits EUR 45-120M of capex, the structure of the sales organization and the competitive timeline: the three routes were assessed against the same grid (time-to-market, customer control, capex, execution risk)." },
  options: [
    { name: "Build", points: ["Proprietary platform in 24 months", "EUR 120M capex, full control of the roadmap", "High execution risk: 40 tech hires", "Time-to-market incompatible with the competitive window"] },
    { name: "Acquire", points: ["Target identified: Novaserv (EUR 34M revenue, profitable)", "Immediate access to 2,100 contracts and 60 technicians", "Estimated premium 9-11x EBITDA (market at 8x)", "Main risk: contract retention at announcement"] },
    { name: "Partner", points: ["JV with an established IoT vendor (2 candidates)", "EUR 45M capex, 12-month time-to-market", "60/40 margin split on the premium tier", "Technology dependence to be framed contractually"] }],
  reco: { body: "Acquire Novaserv then migrate its contracts to a partner platform: the speed of the acquisition, the economics of the partnership." },
  source: SRC, page: P() });

// 6. registerTable
tpl.registerTable(pres.addSlide(), { eyebrow: "RISKS", tracker: { ...TRK, active: 3 },
  title: "Five major risks are identified, three require action before launch",
  exhibit: "Program risk register, July 2026 assessment",
  headers: ["Risk", "Impact", "Probability", "Mitigation", "Owner"],
  widths: [3, 1, 1, 3.4, 1.2],
  rows: [
    ["Senior technician attrition", "High", "Medium", "Targeted retention plan (installed-base bonus + expert track) before the announcement", "HR"],
    ["Contracts cannibalizing new sales", "Medium", "High", "Linked pricing: equipment discount conditional on a 5-year contract", "Sales Dir."],
    ["Novaserv integration slower than planned", "High", "Medium", "Dedicated integration team, synergy milestones at 6/12/18 months", "PMO"],
    ["Price reaction from independents", "Medium", "High", "Segment: predictive premium where data creates the gap", "Strategy"],
    ["Platform capex overrun", "High", "Low", "Capped partner architecture, quarterly review", "CIO"]],
  bottomLine: "Risks 1 and 3 drive the timeline: address them before the program's public announcement.",
  bandLabel: "Reading", source: SRC, page: P() });

// 7. timelineBlocks
tpl.timelineBlocks(pres.addSlide(), { eyebrow: "TRAJECTORY", tracker: { ...TRK, active: 3 },
  title: "The shift executes in four phases over 30 months, with no shock to the core market",
  phases: [
    { label: "Secure", milestone: "M0-M6", body: "Novaserv closing and retention plan for the 60 technicians; design of the managed offer and of the linked equipment + contract pricing; contracting of the partner platform; recruitment of the installed-base sales core team (8 people)." },
    { label: "Prove", milestone: "M6-M12", body: "Pilot on 400 connected sites in the North region: measurement of the attach rate (go/no-go threshold: 20%), of actual margin per contract and of satisfaction; premium pricing adjustment; first cohort of 40 technicians trained in predictive maintenance." },
    { label: "Deploy", milestone: "M12-M24", body: "Roll-out in regional waves (North, East, Rhone, West, South), migration of the 2,100 Novaserv contracts to the target platform, training of 300 technicians, build-up of forward stock in the 12 regional hubs." },
    { label: "Optimize", milestone: "M24-M30", body: "Predictive maintenance generalized across the connected base (target: 11,000 sites), upgrade of standard contracts to premium, supplier renegotiation on consolidated parts volumes, preparation of the Benelux extension." }],
  source: SRC, page: P() });

// 8. insightProof
tpl.insightProof(pres.addSlide(), { eyebrow: "CONVICTION", tracker: TRK,
  title: "The installed base's usage data is the asset competitors cannot replicate",
  claim: "18,400 sites, 11 years of failure history: no one else can train a predictive model on this depth.",
  proofs: [
    { head: "38% of failures are predictable", body: "Measured on the 6,800 connected sites, from signals 90 days before incident." },
    { head: "-22% intervention cost with predictive", body: "A planned intervention avoids the emergency call-out and the express part." },
    { head: "Customers pay for uptime", body: "In 34 of the 42 interviews, production downtime weighs more than the contract price." }],
  source: SRC, page: P() });

// 9. nColCards
tpl.nColCards(pres.addSlide(), { eyebrow: "MINUTES", tracker: { ...TRK, active: 2 },
  title: "The June 12 committee approved the principle and framed three open questions", tintAlt: true,
  cards: [
    { head: "Discussed", body: ["Market diagnosis shared without reservation", "Debate on the pace: 24 vs 30 months", "HR concern about the training load", "CFO question on sensitivity to the attach rate", "Premium price positioning deemed defensible"] },
    { head: "Decided", body: ["Principle of the services shift approved unanimously", "EUR 1.2M M&A study budget released", "North pilot confirmed for Q1 2027", "Go/no-go threshold set: attach rate of 20% or more", "Monthly reporting to the strategy committee"] },
    { head: "Open questions", body: ["Exact scope of the premium offer (SLAs, exclusions)", "Handling of ongoing independent contracts", "Timeline for communicating to field teams", "Future of the Novaserv brand after closing", "Fit with the 2027 plant capex plan"] }],
  source: "Source: strategy committee decision log, June 12, 2026", page: P() });

// 10. exhibitInsights
tpl.exhibitInsights(pres.addSlide(), { eyebrow: "EVIDENCE", tracker: TRK,
  title: "Services margin is 2.3 times higher than equipment margin, and the gap is widening",
  exhibit: { header: "Gross margin by activity, %, 2021-2025",
    draw: (s, z) => s.addChart(pres.charts.BAR, [
      { name: "Equipment", labels: ["2021","2022","2023","2024","2025"], values: [22.4, 21.8, 21.1, 20.6, 20.1] },
      { name: "Services",  labels: ["2021","2022","2023","2024","2025"], values: [41.2, 42.5, 43.6, 44.8, 46.0] }],
      kit.chartLight({ x: z.x, y: z.y, w: z.w, h: z.h, barDir: "col",
        chartColors: [kit.THEME.neg, kit.THEME.accent], showLegend: true, legendPos: "b",
        dataLabelFontSize: 10, valAxisHidden: true })) },
  insights: [
    "Services margin reaches 46% in 2025 versus 20% for equipment, and has been growing 1.2 points per year since 2021. [F]",
    "The gap comes from the mix: multi-year contracts smooth travel costs and raise technician utilization from 61% to 78%. [I]",
    "Each point of services mix adds roughly 0.55 point of group margin: the 35% mix target lifts group margin from 28% to 34%. [E]"],
  source: SRC, page: P() });

// 11. recoOnePager
tpl.recoOnePager(pres.addSlide(), { eyebrow: "RECOMMENDATION", tracker: { ...TRK, active: 2 },
  title: "We recommend acquiring Novaserv and shifting 60% of capex to services",
  reco: { text: "Acquire Novaserv (offer at 9.5x EBITDA maximum), migrate its contracts to the partner platform, and reallocate 60% of 2027-2029 capex to managed services.", date: "Committee of September 18, 2026" },
  why: { points: [
    "It is the only option combining speed (12-month time-to-market) with control of the end-customer relationship.",
    "The return is measurable: EUR 38M of additional EBITDA in year 3, full payback in 4.2 years in the base case.",
    "Execution risk is bounded: the 400-site pilot validates every assumption before the roll-out."] },
  actions: [
    { tag: "D1", head: "Mandate the investment bank", sub: "Novaserv letter of intent before end of October" },
    { tag: "D2", head: "Release the pilot budget (EUR 8.5M)", sub: "team, connectivity, premium offer in the North" },
    { tag: "D3", head: "Appoint the executive sponsor", sub: "ExCo member dedicated at 50% minimum" }],
  source: SRC, page: P() });

// 12. buckets
tpl.buckets(pres.addSlide(), { eyebrow: "STRUCTURE", tracker: { ...TRK, active: 1 },
  title: "The maintenance value leakage plays out across four distinct, cumulative pockets",
  buckets: [
    { head: "Standard contracts", sub: "EUR 42M capturable", points: ["8,900 sites without any contract", "Entry-level offer at EUR 2,400/year", "Channel: dedicated installed-base campaign", "Target conversion rate: 20% in 3 years", "Acquisition cost: 5x lower than new sales"] },
    { head: "Predictive premium", sub: "EUR 31M capturable", points: ["6,800 sites already connected", "35% premium vs the standard contract", "Differentiated by 11 years of data", "38% of failures predictable at 90 days", "Intervention cost reduced by 22%"] },
    { head: "Spare parts", sub: "EUR 19M capturable", points: ["Current capture rate: only 31%", "Lever: forward stock in 12 hubs", "Parts gross margin: 52%", "Sold by default with the premium contract", "Next-day delivery = the argument against independents"] },
    { head: "Training & audit", sub: "EUR 8M capturable", points: ["Regulatory requirement as of January 1, 2027", "Packaged with the maintenance contract", "High margin (61%), low volume", "Entry point into customers without a contract", "Capacity: 15 auditors to certify by end 2026"] }],
  bottomLine: "EUR 100M of annual revenue capturable on the existing base, without selling a single new unit.",
  bandLabel: "Sum", source: SRC, page: P() });

// 13. scenarioCards
tpl.scenarioCards(pres.addSlide(), { eyebrow: "SCENARIOS", tracker: { ...TRK, active: 2 },
  title: "Even in the low scenario, the shift creates more value than the current plan",
  hero: 1,
  scenarios: [
    { name: "Low scenario", tag: "Slow adoption", metrics: [["Services mix 2029", "28%"], ["EBITDA 2029", "EUR 118M"], ["Payback", "5.8 yrs"], ["NPV at 9%", "+EUR 64M"]], notes: "Pilot attach rate at 18%, Novaserv migration in 24 months, no price premium." },
    { name: "Base case", tag: "Pilot trajectory", metrics: [["Services mix 2029", "35%"], ["EBITDA 2029", "EUR 152M"], ["Payback", "4.2 yrs"], ["NPV at 9%", "+EUR 147M"]], notes: "26% attach rate (measured on the North pilot), 8% predictive premium, Novaserv synergies at 12 months." },
    { name: "High scenario", tag: "Fast shift", metrics: [["Services mix 2029", "41%"], ["EBITDA 2029", "EUR 176M"], ["Payback", "3.4 yrs"], ["NPV at 9%", "+EUR 215M"]], notes: "The 2027 regulation accelerates the mandatory audit, 31% attach rate, extension to the Benelux base." }],
  bottomLine: "The decision's break-even is a 14% attach rate: the pilot measured 26%.",
  bandLabel: "Sensitivity", source: SRC, page: P() });

// 14. steeringCommittee
tpl.steeringCommittee(pres.addSlide(), { eyebrow: "STEERCO — JULY 2026", tracker: { ...TRK, active: 3 },
  title: "The program is green on the pilot, two decisions gate wave 2",
  statuses: [
    { label: "Overall progress", status: "green", text: "On plan" },
    { label: "Budget", status: "green", text: "94% on track" },
    { label: "Tech recruitment", status: "amber", text: "12/18 filled" },
    { label: "Novaserv integration", status: "amber", text: "M6 milestone at risk" }],
  progress: ["North pilot: 412 sites equipped, 26% attach rate", "Premium offer legally validated in 3 regions", "Migration of the first 700 Novaserv contracts completed"],
  decisions: ["Approve the pilot extension to the East region (EUR 2.1M)", "Decide parts pricing for standard contracts", "Confirm the internal announcement date for the program (W38)"],
  risks: ["Senior attrition: 4 departures in Q2, retention plan to be reinforced", "Platform dependence: partner SLA under review", "Training delay: 12 trained out of 18 planned at W28"],
  source: "Source: program reporting W28; Meridio PMO", page: P() });

// 15. stackedBands
tpl.stackedBands(pres.addSlide(), { eyebrow: "CUSTOMER FINDINGS", tracker: { ...TRK, active: 1 },
  title: "The 42 customer interviews converge: uptime outweighs price",
  bands: [
    { head: "Production downtime costs more than the contract", body: "An unplanned stoppage costs a median EUR 34k per day; the premium contract costs EUR 3.3k per year.", kpis: [["EUR 34k", "cost per day of downtime"], ["81%", "cite uptime first"]] },
    { head: "Trust in predictive maintenance already exists", body: "Connected customers accept sharing usage data as long as the benefit is contractualized.", kpis: [["74%", "willing to share"], ["+8-12%", "accepted premium"]] },
    { head: "Independents win on proximity, not quality", body: "Choosing an independent maintainer is a choice of perceived responsiveness: exactly Meridio's field advantage.", kpis: [["61%", "cite responsiveness"], ["2 hrs", "median Meridio lead time"]] }],
  source: "Source: 42 customer interviews, April-June 2026; Sprint OS analysis", page: P() });

// 16. decisionCockpit
tpl.decisionCockpit(pres.addSlide(), { eyebrow: "TRADE-OFFS", tracker: { ...TRK, active: 2 },
  title: "Four trade-offs structure the September committee",
  decisions: [
    { area: "M&A scope", context: "The Novaserv offer expires September 30; a second player (Techniparc) is being approached by a fund.", reco: "Firm offer at 9.5x EBITDA maximum, 60-day exclusivity.", ifNot: "Likely loss of the target to the fund; the alternative is 18 months slower." },
    { area: "Roll-out pace", context: "The pilot supports a roll-out in 18 or 24 months depending on training capacity.", reco: "24 months: align the waves with the existing training cohorts.", ifNot: "Default decision = 24 months, but without securing external trainers." },
    { area: "Linked pricing", context: "The equipment discount conditional on a 5-year contract cannibalizes 4 points of new-sales margin.", reco: "Accept the cannibalization: the contract NPV covers 2.6x the discount.", ifNot: "Sales reps will sell equipment without attach, reproducing the current leakage." },
    { area: "Program governance", context: "The program spans five departments; current steering is handled part-time by Strategy.", reco: "ExCo sponsor dedicated at 50% + a 4-person PMO.", ifNot: "Each department optimizes locally; the M12 timeline becomes untenable." }],
  source: SRC, page: P() });

// 17. phasesRoadmap
tpl.phasesRoadmap(pres.addSlide(), { eyebrow: "FIRST 100 DAYS", tracker: { ...TRK, active: 3 },
  title: "The first 100 days secure the acquisition, the teams and the pilot",
  phases: [
    { name: "Mobilize", span: "Days 0-30", items: [ { head: "Novaserv letter of intent", sub: "bank mandated, data room open" }, { head: "Retention plan signed", sub: "18 senior technicians targeted" }, { head: "Program team appointed", sub: "sponsor + PMO + 5 leads" }] },
    { name: "Prove", span: "Days 31-60", items: [ { head: "Premium offer finalized", sub: "pricing, SLAs, contract template" }, { head: "North pilot contracted", sub: "400 sites, 3 waves" }, { head: "Novaserv due diligence", sub: "focus on contract retention" }] },
    { name: "Anchor", span: "Days 61-100", items: [ { head: "Novaserv signing", sub: "closing targeted at M5" }, { head: "First 100 pilot contracts", sub: "attach rate measured" }, { head: "Training plan launched", sub: "first cohort of 40" }] }],
  bottomLine: "100-day exit milestone: pilot attach rate of 20% or more, otherwise review the investment case.",
  bandLabel: "Checkpoint", source: SRC, page: P() });

// 18. canvasGrid
tpl.canvasGrid(pres.addSlide(), { eyebrow: "TARGET OPERATING MODEL", tracker: { ...TRK, active: 3 },
  title: "The target operating model is organized around installed-base data", gridCols: 3, focal: 4,
  cells: [
    { head: "Ambition", body: "35% services mix by 2029, 34% group margin, French leader in industrial predictive maintenance." },
    { head: "Offer", body: "Three tiers: standard contract, predictive premium, regulatory audit & training." },
    { head: "Sales", body: "Dedicated installed-base force (24 people), compensation tied to attach and renewal." },
    { head: "Operations", body: "Centralized intervention planning, forward stock in 12 regional hubs." },
    { head: "Installed-base data", body: "11 years of history, 6,800 connected sites: the engine of predictive maintenance and pricing." },
    { head: "Technology", body: "Partner platform (JV), ERP integration in 3 waves, no heavy proprietary development." },
    { head: "Talent", body: "300 technicians trained in predictive maintenance, expert track created, certification bonus." },
    { head: "Governance", body: "ExCo sponsor, monthly SteerCo, quarterly value review on 5 KPIs." },
    { head: "Performance", body: "Attach rate, margin per contract, base uptime, NPS, parts capture." }],
  source: SRC, page: P() });

// 19. lanesMatrix
tpl.lanesMatrix(pres.addSlide(), { eyebrow: "TARGET CUSTOMER JOURNEY", tracker: { ...TRK, active: 3 },
  title: "The target journey engages the customer from installation, not after the first failure",
  steps: ["Installation", "Commissioning", "Operation", "Renewal"],
  lanes: [
    { label: "Customer", cells: ["Chooses the linked equipment + contract offer", "Activates connected monitoring with the technician", "Receives alerts and uptime reports", "Renews based on the value report"] },
    { label: "Front office", cells: ["Sells the discount conditional on the 5-year contract", "Schedules the D+30 calibration visit", "Annual on-site review with quantified results", "Proposes the premium upgrade 6 months before term"] },
    { label: "Back office", cells: ["Registers the site and its alert thresholds", "Connects the sensors to the platform", "Schedules the predictive interventions", "Prepares the automated value report"] },
    { label: "Data & systems", cells: ["Site created in the installed-base repository", "Sensor feed active, 30-day baseline", "Predictive model: 90-day alerts", "Versioned site health score"] }],
  bottomLine: "Each step of the journey feeds the data that makes the next step more profitable.",
  bandLabel: "Logic", source: SRC, page: P() });

// 20. mosaic (bento: 1 hero + tiles)
tpl.mosaic(pres.addSlide(), { eyebrow: "PROGRAM AT A GLANCE", tracker: { ...TRK, active: 3 },
  title: "One program, five moving parts, a single north-star metric",
  hero: { head: "EUR 100M of annual revenue is capturable on the existing base",
    body: "Standard contracts, predictive premium, parts and training: four pockets, all built on assets already paid for. The north-star metric is the contract attach rate: the pilot measured 26% against a 14% break-even.\n\nEverything in this program either raises the attach rate or raises the value of an attached contract." },
  tiles: [
    { head: "Pilot", body: "412 sites equipped in the North region.", kpi: ["26%", "attach rate"] },
    { head: "M&A", body: "Novaserv: 2,100 contracts, 60 technicians.", kpi: ["9.5x", "EBITDA cap"] },
    { head: "People", body: "Predictive-maintenance training track.", kpi: ["300", "technicians"] },
    { head: "Platform", body: "Partner JV, ERP integration in 3 waves.", kpi: ["12 mo", "time-to-market"] },
    { head: "Finance", body: "EBITDA doubles in the base case.", kpi: ["152", "EBITDA 2029, EUR M"] }],
  source: SRC, page: P() });

// ─────────────────────────── EXHIBIT GALLERY ───────────────────────────
// Divider (dark structure page)
kit.dividerDark(pres.addSlide(), { part: "Appendix", title: "Exhibit gallery",
  caption: "The same case, told through every exhibit family of the kit: native charts, SVG exhibits, craft primitives, dark KPI strip." });

// G1. Native charts I — doughnut + radar
{
  const s = pres.addSlide();
  kit.frameLight(s, "EXHIBITS — NATIVE CHARTS I",
    "Standard contracts hold the largest capturable pocket, and Meridio outscores rivals on every capability but price",
    "Doughnut (share of a whole) and radar (multi-criteria profile), both native pptxgenjs charts.");
  const [L, R2] = kit.cols([1, 1], { top: 2.2 });
  kit.exhibitHeader(s, "Capturable revenue by pocket, EUR M/yr", L.x, L.y - 0.02, L.w);
  kit.doughnutChart(s, { x: L.x, y: L.y + 0.35, w: L.w - 0.3, h: L.h - 0.55, slices: [
    { label: "Standard contracts", value: 42 }, { label: "Predictive premium", value: 31 },
    { label: "Spare parts", value: 19 }, { label: "Training & audit", value: 8 }] });
  kit.exhibitHeader(s, "Capability profile vs best competitor, 0-5 scale", R2.x, R2.y - 0.02, R2.w);
  kit.radarChart(s, { x: R2.x, y: R2.y + 0.35, w: R2.w - 0.2, h: R2.h - 0.55,
    axes: ["Field coverage", "Usage data", "Brand", "Digital tools", "Price"],
    series: [ { name: "Meridio", values: [4.8, 4.5, 4.1, 3.2, 2.9] }, { name: "Best competitor", values: [3.1, 2.2, 3.6, 3.8, 3.9] }] });
  kit.source(s, SRC, P());
}

// G2. Native charts II — combo (bars + line, 2nd axis) + positioning scatter map
{
  const s = pres.addSlide();
  kit.frameLight(s, "EXHIBITS — NATIVE CHARTS II",
    "Revenue grows moderately while the services mix does the heavy lifting, and no rival combines coverage with digital reach",
    "Combo chart (two magnitudes, secondary axis) and positioning map (named quadrants, named points).");
  const [L, R2] = kit.cols([1.15, 1], { top: 2.2 });
  kit.exhibitHeader(s, "Revenue (EUR M, bars) and services mix (%, line), 2025-2029E", L.x, L.y - 0.02, L.w);
  kit.comboBarLine(s, { x: L.x, y: L.y + 0.35, w: L.w - 0.25, h: L.h - 0.55,
    cats: ["2025", "2026", "2027", "2028", "2029"],
    bar: { name: "Revenue (EUR M)", values: [850, 858, 875, 897, 920] },
    line: { name: "Services mix (%)", values: [22, 24, 28, 32, 35] } });
  kit.exhibitHeader(s, "Competitive positioning, 2026", R2.x, R2.y - 0.02, R2.w);
  kit.scatterMap(s, { x: R2.x, y: R2.y + 0.3, w: R2.w, h: R2.h - 0.5,
    xLabel: "Digital & predictive capability", yLabel: "Field coverage",
    quadrants: ["Local champions", "Winners", "Niche players", "Digital attackers"],
    points: [ { label: "Meridio", x: 0.6, y: 0.76, highlight: true }, { label: "Indep. networks", x: 0.18, y: 0.62 },
      { label: "Techniparc", x: 0.55, y: 0.38 }, { label: "IoT entrants", x: 0.82, y: 0.22 }] });
  kit.source(s, SRC, P());
}

// G3. SVG exhibits I — slope + dumbbell (before / after)
{
  const s = pres.addSlide();
  kit.frameLight(s, "EXHIBITS — SVG (COMPARISONS)",
    "Group margin gains six points by 2029, driven by three operational shifts on the installed base",
    "Slope chart (two periods) and dumbbell (today vs target), rendered by the SVG engine.");
  const [L, R2] = kit.cols([1, 1.1], { top: 2.2 });
  kit.exhibitHeader(s, "Margin by segment, %, 2025 vs 2029E", L.x, L.y - 0.02, L.w);
  s.addImage({ path: svgSlope, x: L.x + 0.1, y: L.y + 0.4, w: 4.9, h: 3.5 });
  kit.exhibitHeader(s, "Operational levers, today vs 2029 target", R2.x, R2.y - 0.02, R2.w);
  s.addImage({ path: svgDumbbell, x: R2.x + 0.15, y: R2.y + 0.55, w: 5.5, h: 3.1 });
  kit.source(s, SRC, P());
}

// G4. SVG exhibits II — mekko + waffle + venn
{
  const s = pres.addSlide();
  kit.frameLight(s, "EXHIBITS — SVG (STRUCTURE)",
    "Services reach 35% of a richer mix, while parts capture and the premium sweet spot remain wide open",
    "Marimekko (two-dimensional mix), waffle (memorable proportion) and Venn (where the premium wins).");
  const zs = kit.cols([1.15, 1.25, 1], { top: 2.2 });
  kit.exhibitHeader(s, "2029E revenue mix", zs[0].x, zs[0].y - 0.02, zs[0].w);
  s.addImage({ path: svgMekko, x: zs[0].x, y: zs[0].y + 0.45, w: zs[0].w - 0.15, h: (zs[0].w - 0.15) * 0.714 });
  kit.exhibitHeader(s, "Parts spend captured", zs[1].x, zs[1].y - 0.02, zs[1].w);
  s.addImage({ path: svgWaffle, x: zs[1].x, y: zs[1].y + 0.75, w: zs[1].w - 0.1, h: (zs[1].w - 0.1) * 0.585 });
  kit.exhibitHeader(s, "Premium sweet spot", zs[2].x, zs[2].y - 0.02, zs[2].w);
  s.addImage({ path: svgVenn, x: zs[2].x + 0.1, y: zs[2].y + 0.42, w: zs[2].w - 0.35, h: (zs[2].w - 0.35) * 0.909 });
  kit.source(s, SRC, P());
}

// G5. Craft primitives — waterfall + 2x2 matrix
{
  const s = pres.addSlide();
  kit.frameLight(s, "EXHIBITS — CRAFT PRIMITIVES",
    "The EBITDA bridge to 2029 rests on four positive levers that absorb the planned cannibalization",
    "Waterfall (value bridge) and 2x2 matrix (value vs effort), drawn as native shapes.");
  const [L, R2] = kit.cols([1.35, 1], { top: 2.25 });
  kit.exhibitHeader(s, "EBITDA bridge 2025 -> 2029E, EUR M (base case)", L.x, L.y - 0.02, L.w);
  kit.waterfall(s, [
    { label: "EBITDA 2025", value: 76, total: true }, { label: "Novaserv", value: 20 },
    { label: "Service contracts", value: 34 }, { label: "Parts capture", value: 18 },
    { label: "Predictive premium", value: 12 }, { label: "Cannibalization", value: -8 },
    { label: "EBITDA 2029", value: 152, total: true }],
    L.x, L.y + 0.6, L.w - 0.3, L.h - 1.35, { fmt: v => v });
  kit.exhibitHeader(s, "Initiatives: value created vs delivery effort", R2.x, R2.y - 0.02, R2.w);
  kit.matrix2x2(s, R2.x + 0.75, R2.y + 0.5, R2.w - 1.1, R2.h - 1.15, {
    xlabel: "Delivery effort", ylabel: "Value created",
    items: [ { x: 0.22, y: 0.82, label: "Std contracts" }, { x: 0.55, y: 0.9, label: "Premium" },
      { x: 0.3, y: 0.45, label: "Parts hubs" }, { x: 0.78, y: 0.62, label: "Novaserv" },
      { x: 0.7, y: 0.25, label: "Benelux ext." }] });
  kit.source(s, SRC, P());
}

// G6. Dark KPI strip — native gradient tiles + glow on the big numbers
{
  const s = pres.addSlide();
  kit.darkHeader(s, null, "THE PROGRAM IN FOUR NUMBERS", "EBITDA doubles by 2029, on assets already paid for");
  kit.metricStrip(s, [
    ["x2", "EBITDA by 2029 (76 -> 152 EUR M, base case)"],
    ["26%", "pilot attach rate (break-even: 14%)"],
    ["EUR 100M", "capturable revenue on the existing base"],
    ["94%", "field coverage within 2 hours"]],
    0.55, 2.7, 12.2, { dark: true, h: 1.7, size: 30 });
  s.addText("Dark KPI strip: native gradient tiles (effects.py) + subtle glow on the figures — reserved for the numbers that carry the story.", {
    x: 0.55, y: 5.1, w: 12.2, h: 0.5, fontFace: kit.THEME.fBody, fontSize: 12.5, italic: true, color: kit.THEME.dmute, margin: 0 });
  kit.source(s, SRC, P());
}

// Closing
kit.coverDark(pres.addSlide(), { eyebrow: "NEXT STEPS", title: "Decide in September",
  governing: "Three decisions at the September 18 committee: M&A mandate, pilot budget, executive sponsor. The decision's break-even is a 14% attach rate; the pilot measured 26%.",
  metaA: "Contact: Strategy team", metaB: "strategy@meridio.example", metaC: "Sprint OS Deck Builder", metaD: "Golden deck — demo", source: SRC });

const out = path.join(outdir, "golden-deck.pptx");
await pres.writeFile({ fileName: out });
console.log("OK " + out);

})();
